version: "3.8"
services:
  postgres:
    image: postgres:17.2-alpine3.20
    container_name: todo-node-ansible-lab-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todoapp
      DB_HOST: postgres
    volumes:
      - todo-node-ansible-lab_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  todo-node-ansible-lab_postgres_data:
